"""
Django settings for devops project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v6zx=ezke-)(32v4)69o6@)r*+o=au23smm(%xp#0darw&4acm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pure_pagination',
    'djcelery',
    'dashboard',
    'resources',
    'work_order',
    'projects',
    'tasks',
    'code_release',
    'books',
    'monitor',
    'audit',
    'games',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
     # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+"/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'devops.context_processors.global_variable',
            ],
        },
    },
]

WSGI_APPLICATION = 'devops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
      'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'devops6',
        'HOST': '127.0.0.1',
        'USER': 'root',
        'PASSWORD': 'root123',
        'PORT': 3306,
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'PRC'
# TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

######## ADD conf  ###
AUTH_USER_MODEL = 'dashboard.UserProfile'

STATICFILES_DIRS = (
            os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = "/login/"

JUMP_PAGE = "jump.html"


PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 5,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

GITLAB_HTTP_URI = "http://zabbix.16801.com:8080/"
GITLAB_TOKEN = "cvEwD9BCFJiX4T6jAwN2"

Jenkins_HTTP_URI =  'http://zabbix.16801.com:8088/'
Jenkins_User = 'admin'
Jenkins_User_API_Token = 'admin12345'

EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "denghonglin0@163.com"
EMAIL_HOST_PASSWORD = "Dhl@12345#@!"
EMAIL_USE_TLS = False
EMAIL_FROM = "denghonglin0@163.com"


ZABBIX_API = "http://211.159.170.73/"
ZABBIX_USER = "Admin"
ZABBIX_USERPASS = "ZabBix@16801.Com"

### audit conf ###
MULTI_TASK_SCRIPT = os.path.join(BASE_DIR, 'apps/audit/multitask.py')
FILE_UPLOADS = os.path.join(BASE_DIR,'media/uploads')
FILE_DOWNLOADS = os.path.join(BASE_DIR,'media/downloads')


SHELLINABOX = {
    'host': '127.0.0.1',
    'port': 9000,
    'username': 'root',
    # 'password': '123456'
}

###audit END ####


"""
LOGGING = {
    "version": 1,
    'disable_existing_loggers': False,

    "loggers":{

        "opsweb": {
            "level": "DEBUG",
            "handlers": ["opsweb_file_handle"],
            'propagate': True,
        },

        "django":{
            "level": "DEBUG",
            "handlers": [ "django_handle"],
            'propagate': True,
        },

        "report":{
            "level": "ERROR",
            "handlers": [ "mail"],
            'propagate': True,
        }
    },


    "handlers": {

        "opsweb_file_handle": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "opsweb.log"),
            "formatter": "opsweb"
        },

        "django_handle": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "django.log"),
            "formatter": "opsweb"
        },

        'django_request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, "logs", 'request.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'opsweb',
        },

        "mail":{
            "class": "logging.handlers.SMTPHandler",
            "level": "ERROR",
            "formatter": "simple",
            "mailhost":("smtp.139.com", 25),
            "fromaddr":"13260071987@139.com",
            "toaddrs":["597004635@qq.com"],
            "subject" : "devops mail",
            "credentials" :("13260071987@139.com","yi15093547036")
        }
    },

    'formatters': {
        'opsweb':{
            'format': '[%(asctime)s] [%(process)d] [%(thread)d] [%(filename)16s:%(lineno)4d] [%(levelname)-6s] %(message)s'
        },
        'simple': {
            'format': '%(asctime)s %(levelname)s %(message)s'
        }
    },
}
"""

import djcelery
djcelery.setup_loader()

BROKER_URL = 'redis://127.0.0.1:6379/1'
BROKER_TRANSPORT = 'redis'
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERYD_LOG_FILE = BASE_DIR + "/logs/celery.log"
CELERYD_MAX_TASKS_PER_CHILD = 40


########A END ###
