# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-24 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='chanshort',
        ),
    ]
