# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-24 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_server_chanshort'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='GameServer',
        ),
    ]
