# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True, verbose_name='idc 字母简称')),
                ('idc_name', models.CharField(default='', max_length=100, verbose_name='idc 中文名字')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='具体的地址，云厂商可以不填')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='机房联系电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='机房联系email')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='机房联系人')),
            ],
            options={
                'db_table': 'resources_idc',
                'permissions': (('view_idc', '访问idc列表页面'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=32, verbose_name='业务线的名字')),
                ('module_letter', models.CharField(db_index=True, max_length=10, verbose_name='业务线字母简称')),
                ('op_interface', models.CharField(max_length=150, verbose_name='运维对接人')),
                ('dev_interface', models.CharField(max_length=150, verbose_name='业务对接人')),
                ('pid', models.IntegerField(db_index=True, verbose_name='上级业务线id')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(max_length=20, null=True, verbose_name='云主机/物理机')),
                ('sn', models.CharField(db_index=True, max_length=60, null=True)),
                ('hostname', models.CharField(db_index=True, max_length=50, null=True)),
                ('inner_ip', models.CharField(max_length=32, null=True, unique=True)),
                ('out_ip', models.CharField(max_length=32, null=True)),
                ('server_conf', models.CharField(max_length=100, null=True)),
                ('remark', models.TextField(null=True)),
                ('service_id', models.IntegerField(db_index=True, null=True)),
                ('server_purpose', models.IntegerField(db_index=True, null=True)),
                ('create_date', models.DateField(null=True)),
                ('check_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('idc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Idc')),
            ],
            options={
                'db_table': 'resources_server',
                'ordering': ['id'],
            },
        ),
    ]
