# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
