# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_server_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
