# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-12 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20181012_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Status'),
        ),
    ]
