# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20181012_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Product'),
        ),
    ]
