# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='expire',
            field=models.IntegerField(default=10800, verbose_name='超时时间(s)'),
        ),
    ]
