# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-06 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20181206_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginToken',
            new_name='Token',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='values',
            new_name='val',
        ),
    ]
