# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-17 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20181206_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='command',
            new_name='cmd',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SmallIntegerField(choices=[(0, 'cmd'), (1, 'file_transfer')]),
        ),
    ]
