# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20181217_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeout',
            field=models.IntegerField(default=15, verbose_name='任务超时'),
        ),
    ]
