# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-22 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0006_auto_20181020_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='图形标题')),
                ('subtitle', models.CharField(max_length=50, null=True, verbose_name='图形子标题')),
                ('unit', models.CharField(max_length=10, verbose_name='数据点格式化后的单位, y轴格式化后的单位')),
                ('measurement', models.CharField(max_length=32, verbose_name='influx 表名')),
                ('auto_hostname', models.BooleanField(default=True, verbose_name='是否从业务线取主机名作为条件')),
                ('field_expression', models.CharField(max_length=100, null=True, verbose_name='influx sql where 条件')),
                ('tooltip_formatter', models.CharField(max_length=100, null=True, verbose_name='对tooltip进行格式化')),
                ('yaxis_formatter', models.CharField(max_length=100, null=True, verbose_name='对y轴进行格式化')),
                ('product', models.ManyToManyField(to='resources.Product', verbose_name='与业务线表多对多关联')),
            ],
            options={
                'db_table': 'monitor_influx_graph',
            },
        ),
        migrations.CreateModel(
            name='ZabbixHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.IntegerField(db_index=True, verbose_name='zabbix hostid')),
                ('host', models.CharField(max_length=50, null=True, verbose_name='zabbix hostname')),
                ('ip', models.CharField(db_index=True, max_length=32, verbose_name='zabbix ip')),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.Server')),
            ],
            options={
                'db_table': 'zabbix_cache_host',
            },
        ),
    ]
